name: Super-Linter

on: push

jobs:
  super-lint:
  name: Lint code base
  runs-on: ubuntu-latest
  steps:
    -name: Cheke el codigo
     uses: actions/checkout@v2
    -name: run super-linter
     uses: github/super-linter@v4
     env:
      DEFAULT_BRANCH: main
      
